name: ubuntu

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup prerequisites
        run: |
          sudo apt-get install xsltproc

      - name: XSD documentation generation
        run: |
          make

      - uses: actions/upload-artifact@v2
        with:
          name: published-ubuntu
          path: doc

  deploy-gh-pages:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v2

    - uses: actions/download-artifact@v2
      with:
        name: published-ubuntu
        path: doc

    - uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.GH_DEPLOY_KEY }}
        publish_dir: ./doc
        force_orphan: true
        user_name: ${{ github.actor }}
        user_email: ${{ format('{0}@users.noreply.github.com', github.actor) }}
        commit_message: "${{ format('Deploy to GitHub Pages: {0}', github.sha) }}"
